name: _openapi_repository_internal_models
description: This package provides neccessary models to openapi_repository package.
version: 0.1.0
homepage: https://github.com/djangoflow/list_bloc/tree/master/packages/_openapi_repository_internal_models

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
