name: openapi_generator_tests
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  openapi_repository_annotations:
    path: ../openapi_repository_annotations
  openapi_repository:
    path: ../openapi_repository
  dio: ^5.2.1+1
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lints: ^5.0.0
  build_test: ^2.2.3
  test: ^1.26.2
